FROM balenalib/raspberry-pi-python:3.7-buster

RUN apt-get update

RUN apt-get install build-essential libssl-dev libffi-dev python-dev

RUN apt-get install python3-smbus

WORKDIR /code

RUN pip3 install --upgrade \
  pip \
  cryptography==3.3.2\
  setuptools \
  wheel\
  smbus2 \
  RPi.GPIO \
  automationhat \
  fastapi \
  pydantic \
  uvicorn

COPY ./app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8090"]