FROM balenalib/raspberry-pi-python:3.7-buster

WORKDIR /code

RUN pip3 install --upgrade \
  pip \
  RPi.GPIO \
  automationhat \
  fastapi \
  pydantic \
  uvicorn

COPY ./app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8090"]